#Имя бутылки с опытом.
item: '&eБутыль опыта – &9[&e<level> lvl&9]'

#Сообщения.
messages:
  
  #Помощь по командам.
  help: '&eПоложить опыт в бутылку - &a/ex create'
  #Если игрок вводит число
  #не кратное 10.
  need-multiple: '&сОшибка! &eКоличество опыта должно быть кратно 10.'
  #Если у игрока не хватает опыта.
  low-exp: '&сОшибка! &eНедостаточно опыта!'
  #Игрок ввел неверное количество бутылок.
  amount: '&сОшибка! &eМаксимальное количество бутылок - 64.'
  #У игрока нет права.
  permission: '&fОшибка! У вас нет доступа к этой команде.'